# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/aloos/final_current/version_one 1/version_one/version_one.srcs/sources_1/ip/dist_mem_gen_2/dist_mem_gen_2.xci
# IP: The module: 'dist_mem_gen_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/aloos/final_current/version_one 1/version_one/version_one.srcs/sources_1/ip/dist_mem_gen_2/dist_mem_gen_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/aloos/final_current/version_one 1/version_one/version_one.srcs/sources_1/ip/dist_mem_gen_2/dist_mem_gen_2.xci
# IP: The module: 'dist_mem_gen_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/aloos/final_current/version_one 1/version_one/version_one.srcs/sources_1/ip/dist_mem_gen_2/dist_mem_gen_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
