# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/aloos/complete_final_version/version_one 1/version_one/version_one.srcs/sources_1/ip/blk_mem_gen_4_1/blk_mem_gen_4.xci
# IP: The module: 'blk_mem_gen_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/aloos/complete_final_version/version_one 1/version_one/version_one.srcs/sources_1/ip/blk_mem_gen_4_1/blk_mem_gen_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/aloos/complete_final_version/version_one 1/version_one/version_one.srcs/sources_1/ip/blk_mem_gen_4_1/blk_mem_gen_4.xci
# IP: The module: 'blk_mem_gen_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/aloos/complete_final_version/version_one 1/version_one/version_one.srcs/sources_1/ip/blk_mem_gen_4_1/blk_mem_gen_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
